# Dependencies
markdown            : kramdown
redcarpet           :
  extensions        : []
highlighter         : rouge
gems                : ["jekyll-sitemap", "jekyll-paginate"]

# Permalinks
permalink           : pretty

# Setup
title               : David's Notes
tagline             : 'Personal Notes'
description         : 'CS = Coding + Sharing'
baseurl             : https://yungshenglu.github.io/

author              : Yung-Sheng Lu
name                : 'Yung-Sheng Lu'
url                 : https://yungshenglu.github.io/

paginate            : 5

# Custom vars
version             : 0.1.0
twitter_username    : yungshenglu
github_username     : yungshenglu
